In [1]:
import numpy as np # import Numpy library to generate 

weights = np.around(np.random.uniform(size=6), decimals=2) # initialize the weights
biases = np.around(np.random.uniform(size=3), decimals=2) # initialize the biases

array([0.22, 0.76, 0.62, 0.91, 0.81, 0.39])

In [2]:
x_1 = 0.5 # input 1
x_2 = 0.85 # input 2

print('x1 is {} and x2 is {}'.format(x_1, x_2))

x1 is 0.5 and x2 is 0.85


In [3]:
z_11 = x_1 * weights[0] + x_2 * weights[1] + biases[0]

print('The weighted sum of the inputs at the first node in the hidden layer is {}'.format(z_11))

The weighted sum of the inputs at the first node in the hidden layer is 1.6760000000000002


In [5]:
z_12 = x_1 * weights[2] + x_2 * weights[3] + biases[1]

print('The weighted sum of the inputs at the second node in the hidden layer is {}'.format(z_12))

The weighted sum of the inputs at the second node in the hidden layer is 1.5935


In [6]:
a_11 = 1.0 / (1.0 + np.exp(-z_11))

print('The activation of the first node in the hidden layer is {}'.format(np.around(a_11, decimals=4)))

The activation of the first node in the hidden layer is 0.8424


In [7]:
a_12 = 1.0 / (1.0 + np.exp(-z_12))

print('The activation of the second node in the hidden layer is {}'.format(np.around(a_12, decimals=4)))

The activation of the second node in the hidden layer is 0.8311


In [10]:
z_2 = a_11 * weights[4] + a_12 * weights[5] + biases[2]

print('The weighted sum of the inputs at the third node in the outer layer is {}'.format(z_2))

The weighted sum of the inputs at the third node in the outer layer is 1.2164551560646337


In [11]:
a_2 = 1.0 / (1.0 + np.exp(-z_2))

print('The activation of the outer layer is {}'.format(np.around(a_2, decimals=4)))

The activation of the outer layer is 0.7714


In [12]:
n = 2 # number of inputs
num_hidden_layers = 2 # number of hidden layers
m = [2, 2] # number of nodes in each hidden layer
num_nodes_output = 1 # number of nodes in the output layer

In [13]:
num_nodes_previous = n # number of nodes in the previous layer

network = {} # initialize network an an empty dictionary

# loop through each layer and randomly initialize the weights and biases associated with each node
# notice how we are adding 1 to the number of hidden layers in order to include the output layer
for layer in range(num_hidden_layers + 1): 
    
    # determine name of layer
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_nodes_output
    else:
        layer_name = 'layer_{}'.format(layer + 1)
        num_nodes = m[layer]
    
    # initialize weights and biases associated with each node in the current layer
    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
            'bias': np.around(np.random.uniform(size=1), decimals=2),
        }
    
    num_nodes_previous = num_nodes
    
print(network) # print network

{'layer_1': {'node_1': {'weights': array([0.71, 0.33]), 'bias': array([1.])}, 'node_2': {'weights': array([0.91, 0.94]), 'bias': array([0.13])}}, 'layer_2': {'node_1': {'weights': array([0.51, 0.9 ]), 'bias': array([0.04])}, 'node_2': {'weights': array([0.97, 0.97]), 'bias': array([0.52])}}, 'output': {'node_1': {'weights': array([0.89, 0.15]), 'bias': array([0.26])}}}


In [14]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    
    num_nodes_previous = num_inputs # number of nodes in the previous layer

    network = {}
    
    # loop through each layer and randomly initialize the weights and biases associated with each layer
    for layer in range(num_hidden_layers + 1):
        
        if layer == num_hidden_layers:
            layer_name = 'output' # name last layer in the network output
            num_nodes = num_nodes_output
        else:
            layer_name = 'layer_{}'.format(layer + 1) # otherwise give the layer a number
            num_nodes = num_nodes_hidden[layer] 
        
        # initialize weights and bias for each node
        network[layer_name] = {}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes

    return network # return the network

In [15]:
small_network = initialize_network(5, 3, [3, 2, 3], 1)
small_network

{'layer_1': {'node_1': {'weights': array([0.37, 0.98, 0.17, 0.14, 0.08]),
   'bias': array([0.52])},
  'node_2': {'weights': array([0.47, 0.57, 0.58, 0.61, 0.6 ]),
   'bias': array([0.33])},
  'node_3': {'weights': array([0.99, 0.09, 1.  , 0.31, 0.98]),
   'bias': array([0.85])}},
 'layer_2': {'node_1': {'weights': array([0.45, 0.54, 0.91]),
   'bias': array([0.13])},
  'node_2': {'weights': array([0.88, 0.28, 0.67]), 'bias': array([0.23])}},
 'layer_3': {'node_1': {'weights': array([0.07, 0.46]), 'bias': array([0.57])},
  'node_2': {'weights': array([0.43, 0.12]), 'bias': array([1.])},
  'node_3': {'weights': array([0.04, 0.17]), 'bias': array([0.56])}},
 'output': {'node_1': {'weights': array([0.28, 0.96, 0.07]),
   'bias': array([0.99])}}}

In [16]:
def compute_weighted_sum(inputs, weights, bias):
    return np.sum(inputs * weights) + bias

In [17]:
from random import seed

np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=2)

print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.15 0.74 0.26 0.53 0.01]


In [20]:
weighted_sum = compute_weighted_sum(inputs, small_network['layer_1']['node_1']['weights'], small_network['layer_1']['node_1']['bias'])
weighted_sum

array([1.4199])

In [21]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

In [22]:
node_output = node_activation(weighted_sum)
node_output

array([0.80532274])

In [23]:
def forward_propagate(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

In [24]:
forward_propagate(small_network, inputs)

The outputs of the nodes in hidden layer number 1 is [0.8053, 0.7862, 0.8175]
The outputs of the nodes in hidden layer number 2 is [0.8404, 0.8464]
The outputs of the nodes in hidden layer number 3 is [0.7346, 0.812, 0.6764]


[0.8831]

In [27]:
temp_z = 0.5 * 0.55 - 0.35 * 0.45 + 0.15

print('Result: {}'.format(np.around(temp_z, decimals=3)))

Result: 0.268


In [28]:
temp_a = 1.0 / (1.0 + np.exp(-temp_z))
print('Activation result: {}'.format(np.around(temp_a, decimals=3)))

Activation result: 0.566
